/**
 * security-skills.js — Extended IT-Security skill taxonomy (200+ skills).
 *
 * UMD module: works both server-side (require) and in the browser (window.SECURITY_GROUPS).
 * Each skill is { key (lowercase, substring-matched), label (human readable) }.
 * Keys are chosen to be distinctive to limit false positives with naive matching.
 */
(function (root, factory) {
  const data = factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
  } else {
    root.SECURITY_GROUPS = data.SECURITY_GROUPS;
    root.SECURITY_ROLES = data.SECURITY_ROLES;
  }
})(typeof self !== 'undefined' ? self : this, function () {
  const SECURITY_GROUPS = [
    {
      category: 'Network Security',
      skills: [
        { key: 'firewall', label: 'Firewalls' },
        { key: 'next-generation firewall', label: 'Next-Gen Firewall (NGFW)' },
        { key: 'intrusion detection', label: 'Intrusion Detection (IDS)' },
        { key: 'intrusion prevention', label: 'Intrusion Prevention (IPS)' },
        { key: 'vpn', label: 'VPN' },
        { key: 'ipsec', label: 'IPsec' },
        { key: 'tls', label: 'TLS/SSL' },
        { key: 'network segmentation', label: 'Network segmentation' },
        { key: 'zero trust', label: 'Zero Trust architecture' },
        { key: 'dns security', label: 'DNS security' },
        { key: 'dhcp', label: 'DHCP' },
        { key: 'network access control', label: 'Network Access Control (NAC)' },
        { key: 'wireshark', label: 'Wireshark / packet analysis' },
        { key: 'tcpdump', label: 'tcpdump' },
        { key: 'netflow', label: 'NetFlow analysis' },
        { key: 'proxy', label: 'Proxy / reverse proxy' },
        { key: 'web application firewall', label: 'Web Application Firewall (WAF)' },
        { key: 'ddos', label: 'DDoS mitigation' },
        { key: 'vlan', label: 'VLAN / network design' },
        { key: 'tcp/ip', label: 'TCP/IP networking' },
      ],
    },
    {
      category: 'Application & Web Security',
      skills: [
        { key: 'owasp', label: 'OWASP Top 10' },
        { key: 'sql injection', label: 'SQL Injection' },
        { key: 'cross-site scripting', label: 'Cross-Site Scripting (XSS)' },
        { key: 'csrf', label: 'CSRF' },
        { key: 'ssrf', label: 'SSRF' },
        { key: 'secure coding', label: 'Secure coding' },
        { key: 'sast', label: 'SAST (static analysis)' },
        { key: 'dast', label: 'DAST (dynamic analysis)' },
        { key: 'iast', label: 'IAST' },
        { key: 'software composition analysis', label: 'Software Composition Analysis (SCA)' },
        { key: 'api security', label: 'API security' },
        { key: 'authentication', label: 'Authentication design' },
        { key: 'authorization', label: 'Authorization / access control' },
        { key: 'jwt', label: 'JWT / token security' },
        { key: 'oauth', label: 'OAuth 2.0' },
        { key: 'session management', label: 'Session management' },
        { key: 'input validation', label: 'Input validation' },
        { key: 'devsecops', label: 'DevSecOps' },
        { key: 'threat modeling', label: 'Threat modeling' },
        { key: 'burp suite', label: 'Burp Suite' },
        { key: 'owasp zap', label: 'OWASP ZAP' },
        { key: 'security headers', label: 'HTTP security headers' },
        { key: 'deserialization', label: 'Insecure deserialization' },
      ],
    },
    {
      category: 'Offensive Security / Pentesting',
      skills: [
        { key: 'penetration testing', label: 'Penetration testing' },
        { key: 'ethical hacking', label: 'Ethical hacking' },
        { key: 'red team', label: 'Red teaming' },
        { key: 'metasploit', label: 'Metasploit' },
        { key: 'nmap', label: 'Nmap' },
        { key: 'exploit development', label: 'Exploit development' },
        { key: 'buffer overflow', label: 'Buffer overflow' },
        { key: 'privilege escalation', label: 'Privilege escalation' },
        { key: 'lateral movement', label: 'Lateral movement' },
        { key: 'social engineering', label: 'Social engineering' },
        { key: 'phishing', label: 'Phishing simulation' },
        { key: 'password cracking', label: 'Password cracking' },
        { key: 'hashcat', label: 'Hashcat' },
        { key: 'john the ripper', label: 'John the Ripper' },
        { key: 'reconnaissance', label: 'Reconnaissance / OSINT' },
        { key: 'osint', label: 'OSINT' },
        { key: 'vulnerability scanning', label: 'Vulnerability scanning' },
        { key: 'nessus', label: 'Nessus' },
        { key: 'openvas', label: 'OpenVAS' },
        { key: 'wireless security', label: 'Wireless / Wi-Fi security' },
        { key: 'aircrack', label: 'Aircrack-ng' },
        { key: 'cobalt strike', label: 'Cobalt Strike' },
        { key: 'active directory attacks', label: 'Active Directory attacks' },
        { key: 'bloodhound', label: 'BloodHound' },
        { key: 'mimikatz', label: 'Mimikatz' },
        { key: 'post-exploitation', label: 'Post-exploitation' },
      ],
    },
    {
      category: 'Defensive Security / Blue Team / SOC',
      skills: [
        { key: 'security operations center', label: 'SOC operations' },
        { key: 'siem', label: 'SIEM' },
        { key: 'splunk', label: 'Splunk' },
        { key: 'elastic siem', label: 'Elastic SIEM / ELK' },
        { key: 'qradar', label: 'IBM QRadar' },
        { key: 'microsoft sentinel', label: 'Microsoft Sentinel' },
        { key: 'soar', label: 'SOAR' },
        { key: 'edr', label: 'EDR' },
        { key: 'xdr', label: 'XDR' },
        { key: 'threat hunting', label: 'Threat hunting' },
        { key: 'threat intelligence', label: 'Threat intelligence' },
        { key: 'mitre att&ck', label: 'MITRE ATT&CK' },
        { key: 'log analysis', label: 'Log analysis' },
        { key: 'incident response', label: 'Incident response' },
        { key: 'security monitoring', label: 'Security monitoring' },
        { key: 'intrusion analysis', label: 'Intrusion analysis' },
        { key: 'yara', label: 'YARA rules' },
        { key: 'sigma rules', label: 'Sigma rules' },
        { key: 'dlp', label: 'Data Loss Prevention (DLP)' },
        { key: 'honeypot', label: 'Honeypots' },
        { key: 'use case development', label: 'Detection use-case development' },
      ],
    },
    {
      category: 'Cloud Security',
      skills: [
        { key: 'cloud security', label: 'Cloud security' },
        { key: 'aws security', label: 'AWS security' },
        { key: 'azure security', label: 'Azure security' },
        { key: 'gcp security', label: 'GCP security' },
        { key: 'iam policies', label: 'Cloud IAM policies' },
        { key: 'cspm', label: 'CSPM' },
        { key: 'cwpp', label: 'CWPP' },
        { key: 'kubernetes security', label: 'Kubernetes security' },
        { key: 'container security', label: 'Container security' },
        { key: 'docker security', label: 'Docker security' },
        { key: 'terraform', label: 'Terraform / IaC' },
        { key: 'infrastructure as code', label: 'Infrastructure as Code security' },
        { key: 'cloud native', label: 'Cloud-native security' },
        { key: 'serverless security', label: 'Serverless security' },
        { key: 'aws guardduty', label: 'AWS GuardDuty' },
        { key: 'azure defender', label: 'Microsoft Defender for Cloud' },
        { key: 'secrets management', label: 'Secrets management (Vault)' },
        { key: 'cloud compliance', label: 'Cloud compliance' },
      ],
    },
    {
      category: 'Cryptography & PKI',
      skills: [
        { key: 'cryptography', label: 'Cryptography' },
        { key: 'symmetric encryption', label: 'Symmetric encryption (AES)' },
        { key: 'asymmetric encryption', label: 'Asymmetric encryption (RSA/ECC)' },
        { key: 'hashing', label: 'Hashing (SHA, bcrypt)' },
        { key: 'digital signatures', label: 'Digital signatures' },
        { key: 'public key infrastructure', label: 'PKI' },
        { key: 'certificate management', label: 'Certificate management' },
        { key: 'key management', label: 'Key management (KMS/HSM)' },
        { key: 'tls handshake', label: 'TLS handshake / protocols' },
        { key: 'openssl', label: 'OpenSSL' },
        { key: 'gpg', label: 'GPG / PGP' },
        { key: 'cryptanalysis', label: 'Cryptanalysis' },
      ],
    },
    {
      category: 'Identity & Access Management',
      skills: [
        { key: 'identity and access management', label: 'IAM' },
        { key: 'active directory', label: 'Active Directory' },
        { key: 'azure ad', label: 'Azure AD / Entra ID' },
        { key: 'ldap', label: 'LDAP' },
        { key: 'single sign-on', label: 'Single Sign-On (SSO)' },
        { key: 'saml', label: 'SAML' },
        { key: 'multi-factor authentication', label: 'Multi-Factor Authentication (MFA)' },
        { key: 'privileged access management', label: 'Privileged Access Management (PAM)' },
        { key: 'role-based access control', label: 'RBAC' },
        { key: 'okta', label: 'Okta' },
        { key: 'keycloak', label: 'Keycloak' },
        { key: 'identity governance', label: 'Identity governance' },
      ],
    },
    {
      category: 'GRC, Compliance & Frameworks',
      skills: [
        { key: 'risk assessment', label: 'Risk assessment' },
        { key: 'risk management', label: 'Risk management' },
        { key: 'iso 27001', label: 'ISO/IEC 27001' },
        { key: 'iso 27002', label: 'ISO/IEC 27002' },
        { key: 'nist', label: 'NIST frameworks' },
        { key: 'nist csf', label: 'NIST Cybersecurity Framework' },
        { key: 'gdpr', label: 'GDPR / DSGVO' },
        { key: 'bsi grundschutz', label: 'BSI IT-Grundschutz' },
        { key: 'pci dss', label: 'PCI DSS' },
        { key: 'soc 2', label: 'SOC 2' },
        { key: 'hipaa', label: 'HIPAA' },
        { key: 'security policies', label: 'Security policy development' },
        { key: 'security awareness', label: 'Security awareness training' },
        { key: 'business continuity', label: 'Business continuity (BCM)' },
        { key: 'disaster recovery', label: 'Disaster recovery' },
        { key: 'audit', label: 'Security auditing' },
        { key: 'compliance', label: 'Compliance management' },
        { key: 'data protection', label: 'Data protection' },
        { key: 'vendor risk', label: 'Third-party / vendor risk' },
        { key: 'tisax', label: 'TISAX' },
      ],
    },
    {
      category: 'DFIR & Forensics',
      skills: [
        { key: 'digital forensics', label: 'Digital forensics' },
        { key: 'memory forensics', label: 'Memory forensics' },
        { key: 'disk forensics', label: 'Disk forensics' },
        { key: 'volatility', label: 'Volatility' },
        { key: 'autopsy', label: 'Autopsy / Sleuth Kit' },
        { key: 'ftk', label: 'FTK' },
        { key: 'encase', label: 'EnCase' },
        { key: 'chain of custody', label: 'Chain of custody' },
        { key: 'log forensics', label: 'Log forensics' },
        { key: 'network forensics', label: 'Network forensics' },
        { key: 'incident handling', label: 'Incident handling' },
        { key: 'root cause analysis', label: 'Root cause analysis' },
        { key: 'timeline analysis', label: 'Timeline analysis' },
        { key: 'evidence acquisition', label: 'Evidence acquisition' },
      ],
    },
    {
      category: 'Malware Analysis & Reverse Engineering',
      skills: [
        { key: 'malware analysis', label: 'Malware analysis' },
        { key: 'reverse engineering', label: 'Reverse engineering' },
        { key: 'static analysis', label: 'Static malware analysis' },
        { key: 'dynamic analysis', label: 'Dynamic malware analysis' },
        { key: 'ida pro', label: 'IDA Pro' },
        { key: 'ghidra', label: 'Ghidra' },
        { key: 'x64dbg', label: 'x64dbg / OllyDbg' },
        { key: 'sandboxing', label: 'Sandboxing (Cuckoo)' },
        { key: 'assembly', label: 'Assembly language' },
        { key: 'obfuscation', label: 'Code obfuscation / unpacking' },
        { key: 'ransomware analysis', label: 'Ransomware analysis' },
        { key: 'shellcode', label: 'Shellcode analysis' },
      ],
    },
    {
      category: 'Operating Systems & Infrastructure',
      skills: [
        { key: 'linux', label: 'Linux administration' },
        { key: 'linux hardening', label: 'Linux hardening' },
        { key: 'windows hardening', label: 'Windows hardening' },
        { key: 'windows server', label: 'Windows Server' },
        { key: 'bash', label: 'Bash scripting' },
        { key: 'powershell', label: 'PowerShell' },
        { key: 'python', label: 'Python' },
        { key: 'system administration', label: 'System administration' },
        { key: 'patch management', label: 'Patch management' },
        { key: 'vulnerability management', label: 'Vulnerability management' },
        { key: 'configuration management', label: 'Secure configuration management' },
        { key: 'group policy', label: 'Group Policy (GPO)' },
        { key: 'endpoint security', label: 'Endpoint security' },
        { key: 'antivirus', label: 'Antivirus / EPP' },
        { key: 'backup', label: 'Backup & recovery' },
      ],
    },
    {
      category: 'OT / IoT / Mobile Security',
      skills: [
        { key: 'ot security', label: 'OT / ICS security' },
        { key: 'scada', label: 'SCADA security' },
        { key: 'iot security', label: 'IoT security' },
        { key: 'mobile security', label: 'Mobile security' },
        { key: 'android security', label: 'Android security' },
        { key: 'ios security', label: 'iOS security' },
        { key: 'embedded security', label: 'Embedded security' },
        { key: 'firmware analysis', label: 'Firmware analysis' },
        { key: 'automotive security', label: 'Automotive security' },
        { key: 'modbus', label: 'Modbus / industrial protocols' },
      ],
    },
    {
      category: 'Certifications',
      skills: [
        { key: 'comptia security+', label: 'CompTIA Security+' },
        { key: 'comptia cysa+', label: 'CompTIA CySA+' },
        { key: 'comptia pentest+', label: 'CompTIA PenTest+' },
        { key: 'cissp', label: 'CISSP' },
        { key: 'ccsp', label: 'CCSP' },
        { key: 'cism', label: 'CISM' },
        { key: 'cisa', label: 'CISA' },
        { key: 'ceh', label: 'CEH (Certified Ethical Hacker)' },
        { key: 'oscp', label: 'OSCP' },
        { key: 'oswe', label: 'OSWE' },
        { key: 'gcih', label: 'GIAC GCIH' },
        { key: 'gpen', label: 'GIAC GPEN' },
        { key: 'gsec', label: 'GIAC GSEC' },
        { key: 'crisc', label: 'CRISC' },
        { key: 'security+ ce', label: 'Security+ CE' },
        { key: 'aws certified security', label: 'AWS Certified Security' },
        { key: 'azure security engineer', label: 'Azure Security Engineer (AZ-500)' },
        { key: 'iso 27001 lead auditor', label: 'ISO 27001 Lead Auditor' },
        { key: 'bsi grundschutz praktiker', label: 'BSI Grundschutz-Praktiker' },
      ],
    },
    {
      category: 'Professional & Soft Skills',
      skills: [
        { key: 'communication', label: 'Communication' },
        { key: 'teamwork', label: 'Teamwork' },
        { key: 'documentation', label: 'Technical documentation' },
        { key: 'problem solving', label: 'Problem solving' },
        { key: 'analytical thinking', label: 'Analytical thinking' },
        { key: 'project management', label: 'Project management' },
        { key: 'stakeholder management', label: 'Stakeholder management' },
        { key: 'report writing', label: 'Security report writing' },
        { key: 'presentation', label: 'Presentation skills' },
        { key: 'continuous learning', label: 'Continuous learning' },
      ],
    },
  ];

  // A few extended security roles for richer gap analysis.
  const SECURITY_ROLES = [
    { name: 'SOC Analyst (Tier 1)', required: ['siem', 'log analysis', 'incident response', 'security monitoring', 'communication'] },
    { name: 'Penetration Tester', required: ['penetration testing', 'metasploit', 'nmap', 'burp suite', 'privilege escalation'] },
    { name: 'Cloud Security Engineer', required: ['cloud security', 'aws security', 'kubernetes security', 'iam policies', 'terraform'] },
    { name: 'Incident Responder (DFIR)', required: ['incident response', 'digital forensics', 'memory forensics', 'threat intelligence', 'log analysis'] },
    { name: 'GRC / Security Consultant', required: ['risk assessment', 'iso 27001', 'gdpr', 'audit', 'security policies'] },
    { name: 'Application Security Engineer', required: ['owasp', 'sast', 'secure coding', 'threat modeling', 'api security'] },
    { name: 'Malware Analyst', required: ['malware analysis', 'reverse engineering', 'ghidra', 'static analysis', 'assembly'] },
  ];

  return { SECURITY_GROUPS, SECURITY_ROLES };
});
