/**
 * security-skills.js — Extended IT-Security skill taxonomy (200+ skills).
 *
 * UMD module: works both server-side (require) and in the browser (window.SECURITY_GROUPS).
 * Each skill is { key (lowercase), label (human readable), aliases? (other exact surface
 * forms: acronyms, German and French equivalents) }.
 *
 * Detection lives in skill-matcher.js, which matches on word boundaries: `nist` must not
 * fire inside "administrateur". Aliases only ever hold exact synonyms — paraphrases such
 * as "log correlation" for SIEM are the semantic layer's job (server/embeddings.js).
 */
(function (root, factory) {
  const data = factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
  } else {
    root.SECURITY_GROUPS = data.SECURITY_GROUPS;
    root.SECURITY_ROLES = data.SECURITY_ROLES;
  }
})(typeof self !== 'undefined' ? self : this, function () {
  const SECURITY_GROUPS = [
    {
      category: 'Network Security',
      skills: [
        { key: 'firewall', label: 'Firewalls' },
        { key: 'next-generation firewall', label: 'Next-Gen Firewall (NGFW)' },
        { key: 'intrusion detection', label: 'Intrusion Detection (IDS)', aliases: ['angriffserkennung', 'einbruchserkennung'] },
        { key: 'intrusion prevention', label: 'Intrusion Prevention (IPS)', aliases: ['angriffsprävention'] },
        { key: 'vpn', label: 'VPN' },
        { key: 'ipsec', label: 'IPsec' },
        { key: 'tls', label: 'TLS/SSL' },
        { key: 'network segmentation', label: 'Network segmentation', aliases: ['netzwerksegmentierung'] },
        { key: 'zero trust', label: 'Zero Trust architecture' },
        { key: 'dns security', label: 'DNS security' },
        { key: 'dhcp', label: 'DHCP' },
        { key: 'network access control', label: 'Network Access Control (NAC)', aliases: ['netzzugangskontrolle'] },
        { key: 'wireshark', label: 'Wireshark / packet analysis' },
        { key: 'tcpdump', label: 'tcpdump' },
        { key: 'netflow', label: 'NetFlow analysis' },
        { key: 'proxy', label: 'Proxy / reverse proxy' },
        { key: 'web application firewall', label: 'Web Application Firewall (WAF)', aliases: ['waf'] },
        { key: 'ddos', label: 'DDoS mitigation' },
        { key: 'vlan', label: 'VLAN / network design' },
        { key: 'tcp/ip', label: 'TCP/IP networking', aliases: ['rechnernetz', 'rechnernetze', 'netzwerke', 'netzwerktechnik'] },
      ],
    },
    {
      category: 'Application & Web Security',
      skills: [
        { key: 'owasp', label: 'OWASP Top 10' },
        { key: 'sql injection', label: 'SQL Injection' },
        { key: 'cross-site scripting', label: 'Cross-Site Scripting (XSS)', aliases: ['xss'] },
        { key: 'csrf', label: 'CSRF' },
        { key: 'ssrf', label: 'SSRF' },
        { key: 'secure coding', label: 'Secure coding', aliases: ['sichere programmierung', 'sichere codierung'] },
        { key: 'sast', label: 'SAST (static analysis)', aliases: ['statische code-analyse', 'statische codeanalyse', 'quellcode-analyse', 'source-code'] },
        { key: 'dast', label: 'DAST (dynamic analysis)', aliases: ['dynamische code-analyse'] },
        { key: 'iast', label: 'IAST' },
        { key: 'software composition analysis', label: 'Software Composition Analysis (SCA)' },
        { key: 'api security', label: 'API security', aliases: ['api-sicherheit'] },
        { key: 'authentication', label: 'Authentication design', aliases: ['authentifizierung', 'authentifikation'] },
        { key: 'authorization', label: 'Authorization / access control', aliases: ['autorisierung', 'berechtigungen'] },
        { key: 'jwt', label: 'JWT / token security' },
        { key: 'oauth', label: 'OAuth 2.0' },
        { key: 'session management', label: 'Session management', aliases: ['sitzungsverwaltung'] },
        { key: 'input validation', label: 'Input validation', aliases: ['eingabevalidierung'] },
        { key: 'devsecops', label: 'DevSecOps' },
        { key: 'threat modeling', label: 'Threat modeling', aliases: ['bedrohungsmodellierung'] },
        { key: 'burp suite', label: 'Burp Suite' },
        { key: 'owasp zap', label: 'OWASP ZAP' },
        { key: 'security headers', label: 'HTTP security headers' },
        { key: 'deserialization', label: 'Insecure deserialization' },
      ],
    },
    {
      category: 'Offensive Security / Pentesting',
      skills: [
        { key: 'penetration testing', label: 'Penetration testing', aliases: ['pentest', 'pentests', 'pentesting', 'pen test', 'penetrationstest', 'penetrationstests', 'test d intrusion', 'tests d intrusion'] },
        { key: 'ethical hacking', label: 'Ethical hacking', aliases: ['ethisches hacken'] },
        { key: 'red team', label: 'Red teaming' },
        { key: 'metasploit', label: 'Metasploit' },
        { key: 'nmap', label: 'Nmap' },
        { key: 'exploit development', label: 'Exploit development', aliases: ['exploit-entwicklung', 'ausnutzung'] },
        { key: 'buffer overflow', label: 'Buffer overflow' },
        { key: 'privilege escalation', label: 'Privilege escalation', aliases: ['rechteausweitung'] },
        { key: 'lateral movement', label: 'Lateral movement' },
        { key: 'social engineering', label: 'Social engineering', aliases: ['social-engineering'] },
        { key: 'phishing', label: 'Phishing simulation', aliases: ['phishing-mails'] },
        { key: 'password cracking', label: 'Password cracking' },
        { key: 'hashcat', label: 'Hashcat' },
        { key: 'john the ripper', label: 'John the Ripper' },
        { key: 'reconnaissance', label: 'Reconnaissance / OSINT', aliases: ['aufklärung'] },
        { key: 'osint', label: 'OSINT' },
        { key: 'vulnerability scanning', label: 'Vulnerability scanning', aliases: ['schwachstellenscan', 'schwachstellenanalyse', 'schwachstellen'] },
        { key: 'nessus', label: 'Nessus' },
        { key: 'openvas', label: 'OpenVAS' },
        { key: 'wireless security', label: 'Wireless / Wi-Fi security' },
        { key: 'aircrack', label: 'Aircrack-ng' },
        { key: 'cobalt strike', label: 'Cobalt Strike' },
        { key: 'active directory attacks', label: 'Active Directory attacks' },
        { key: 'bloodhound', label: 'BloodHound' },
        { key: 'mimikatz', label: 'Mimikatz' },
        { key: 'post-exploitation', label: 'Post-exploitation' },
      ],
    },
    {
      category: 'Defensive Security / Blue Team / SOC',
      skills: [
        { key: 'security operations center', label: 'SOC operations' },
        { key: 'siem', label: 'SIEM', aliases: ['security information and event management'] },
        { key: 'splunk', label: 'Splunk' },
        { key: 'elastic siem', label: 'Elastic SIEM / ELK' },
        { key: 'qradar', label: 'IBM QRadar' },
        { key: 'microsoft sentinel', label: 'Microsoft Sentinel' },
        { key: 'soar', label: 'SOAR' },
        { key: 'edr', label: 'EDR' },
        { key: 'xdr', label: 'XDR' },
        { key: 'threat hunting', label: 'Threat hunting', aliases: ['bedrohungssuche'] },
        { key: 'threat intelligence', label: 'Threat intelligence', aliases: ['bedrohungsanalyse'] },
        { key: 'mitre att&ck', label: 'MITRE ATT&CK' },
        // Log/event correlation is a form of log analysis, so it belongs here. It is
        // NOT an alias of `siem`: correlating logs by hand does not prove SIEM tooling,
        // and the gap analysis must keep reporting SIEM as missing.
        { key: 'log analysis', label: 'Log analysis', aliases: ['log correlation', 'event correlation', 'log review', 'correlation de logs', 'correlation d evenements', 'analyse de journaux', 'log-korrelation', 'protokollanalyse', 'ereigniskorrelation', 'log-analyse'] },
        { key: 'incident response', label: 'Incident response', aliases: ['vorfallsbehandlung', 'sicherheitsvorfall', 'sicherheitsvorfälle', 'incident-response'] },
        { key: 'security monitoring', label: 'Security monitoring', aliases: ['sicherheitsüberwachung'] },
        { key: 'intrusion analysis', label: 'Intrusion analysis' },
        { key: 'yara', label: 'YARA rules' },
        { key: 'sigma rules', label: 'Sigma rules' },
        { key: 'dlp', label: 'Data Loss Prevention (DLP)' },
        { key: 'honeypot', label: 'Honeypots' },
        { key: 'use case development', label: 'Detection use-case development' },
      ],
    },
    {
      category: 'Cloud Security',
      skills: [
        { key: 'cloud security', label: 'Cloud security' },
        { key: 'aws security', label: 'AWS security' },
        { key: 'azure security', label: 'Azure security' },
        { key: 'gcp security', label: 'GCP security' },
        { key: 'iam policies', label: 'Cloud IAM policies' },
        { key: 'cspm', label: 'CSPM' },
        { key: 'cwpp', label: 'CWPP' },
        { key: 'kubernetes security', label: 'Kubernetes security' },
        { key: 'container security', label: 'Container security' },
        { key: 'docker security', label: 'Docker security' },
        { key: 'terraform', label: 'Terraform / IaC' },
        { key: 'infrastructure as code', label: 'Infrastructure as Code security' },
        { key: 'cloud native', label: 'Cloud-native security' },
        { key: 'serverless security', label: 'Serverless security' },
        { key: 'aws guardduty', label: 'AWS GuardDuty' },
        { key: 'azure defender', label: 'Microsoft Defender for Cloud' },
        { key: 'secrets management', label: 'Secrets management (Vault)' },
        { key: 'cloud compliance', label: 'Cloud compliance' },
      ],
    },
    {
      category: 'Cryptography & PKI',
      skills: [
        { key: 'cryptography', label: 'Cryptography', aliases: ['kryptographie', 'kryptografie', 'verschlüsselung', 'verschluesselung', 'verschlüsseln', 'entschlüsseln'] },
        { key: 'symmetric encryption', label: 'Symmetric encryption (AES)', aliases: ['symmetrische verschlüsselung'] },
        { key: 'asymmetric encryption', label: 'Asymmetric encryption (RSA/ECC)', aliases: ['asymmetrische verschlüsselung'] },
        { key: 'hashing', label: 'Hashing (SHA, bcrypt)', aliases: ['hashverfahren', 'hashfunktion'] },
        { key: 'digital signatures', label: 'Digital signatures', aliases: ['digitale signatur', 'digitale signaturen'] },
        { key: 'public key infrastructure', label: 'PKI', aliases: ['pki'] },
        { key: 'certificate management', label: 'Certificate management', aliases: ['zertifikatsverwaltung', 'zertifikatsmanagement'] },
        { key: 'key management', label: 'Key management (KMS/HSM)', aliases: ['schlüsselverwaltung', 'schluesselverwaltung'] },
        { key: 'tls handshake', label: 'TLS handshake / protocols' },
        { key: 'openssl', label: 'OpenSSL' },
        { key: 'gpg', label: 'GPG / PGP' },
        { key: 'cryptanalysis', label: 'Cryptanalysis' },
      ],
    },
    {
      category: 'Identity & Access Management',
      skills: [
        { key: 'identity and access management', label: 'IAM', aliases: ['iam', 'identitäts- und zugriffsmanagement', 'identitätsmanagement', 'zugriffsverwaltung'] },
        { key: 'active directory', label: 'Active Directory' },
        { key: 'azure ad', label: 'Azure AD / Entra ID' },
        { key: 'ldap', label: 'LDAP' },
        { key: 'single sign-on', label: 'Single Sign-On (SSO)', aliases: ['sso', 'einmalanmeldung'] },
        { key: 'saml', label: 'SAML' },
        { key: 'multi-factor authentication', label: 'Multi-Factor Authentication (MFA)', aliases: ['mfa', '2fa', 'two-factor authentication', 'zwei-faktor-authentifizierung', 'mehrfaktor-authentifizierung'] },
        { key: 'privileged access management', label: 'Privileged Access Management (PAM)', aliases: ['pam', 'privilegierte zugriffsverwaltung'] },
        { key: 'role-based access control', label: 'RBAC', aliases: ['rbac', 'rollenbasierte zugriffskontrolle'] },
        { key: 'okta', label: 'Okta' },
        { key: 'keycloak', label: 'Keycloak' },
        { key: 'identity governance', label: 'Identity governance' },
      ],
    },
    {
      category: 'GRC, Compliance & Frameworks',
      skills: [
        { key: 'risk assessment', label: 'Risk assessment', aliases: ['risikoanalyse', 'risikobewertung', 'analyse de risques'] },
        { key: 'risk management', label: 'Risk management', aliases: ['risikomanagement'] },
        { key: 'iso 27001', label: 'ISO/IEC 27001', aliases: ['iso27001', 'iso/iec 27001'] },
        { key: 'iso 27002', label: 'ISO/IEC 27002' },
        { key: 'nist', label: 'NIST frameworks' },
        { key: 'nist csf', label: 'NIST Cybersecurity Framework' },
        { key: 'gdpr', label: 'GDPR / DSGVO', aliases: ['dsgvo', 'rgpd', 'datenschutz-grundverordnung', 'general data protection regulation'] },
        { key: 'bsi grundschutz', label: 'BSI IT-Grundschutz', aliases: ['it-grundschutz', 'grundschutz'] },
        { key: 'pci dss', label: 'PCI DSS' },
        { key: 'soc 2', label: 'SOC 2' },
        { key: 'hipaa', label: 'HIPAA' },
        { key: 'security policies', label: 'Security policy development', aliases: ['sicherheitsrichtlinien', 'sicherheitsrichtlinie'] },
        { key: 'security awareness', label: 'Security awareness training', aliases: ['sicherheitsbewusstsein', 'awareness-kampagnen', 'awareness-kampagne', 'sensibilisierung'] },
        { key: 'business continuity', label: 'Business continuity (BCM)', aliases: ['notfallplan', 'notfallpläne', 'notfallmanagement', 'betriebskontinuität'] },
        { key: 'disaster recovery', label: 'Disaster recovery', aliases: ['notfallwiederherstellung', 'wiederherstellung'] },
        { key: 'audit', label: 'Security auditing', aliases: ['audits', 'auditierung', 'sicherheitsaudit', 'sicherheitsaudits', 'it-sicherheitsaudit', 'it-sicherheitsaudits'] },
        { key: 'compliance', label: 'Compliance management', aliases: ['konformität', 'einhaltung'] },
        { key: 'data protection', label: 'Data protection', aliases: ['datenschutz'] },
        { key: 'vendor risk', label: 'Third-party / vendor risk', aliases: ['lieferantenrisiko', 'drittanbieterrisiko'] },
        { key: 'tisax', label: 'TISAX' },
      ],
    },
    {
      category: 'DFIR & Forensics',
      skills: [
        { key: 'digital forensics', label: 'Digital forensics', aliases: ['forensik', 'informatique legale', 'it-forensik', 'digitale forensik'] },
        { key: 'memory forensics', label: 'Memory forensics' },
        { key: 'disk forensics', label: 'Disk forensics' },
        { key: 'volatility', label: 'Volatility' },
        { key: 'autopsy', label: 'Autopsy / Sleuth Kit' },
        { key: 'ftk', label: 'FTK' },
        { key: 'encase', label: 'EnCase' },
        { key: 'chain of custody', label: 'Chain of custody' },
        { key: 'log forensics', label: 'Log forensics' },
        { key: 'network forensics', label: 'Network forensics' },
        { key: 'incident handling', label: 'Incident handling', aliases: ['vorfallbearbeitung'] },
        { key: 'root cause analysis', label: 'Root cause analysis', aliases: ['ursachenanalyse'] },
        { key: 'timeline analysis', label: 'Timeline analysis' },
        { key: 'evidence acquisition', label: 'Evidence acquisition' },
      ],
    },
    {
      // Vulnerability management had no group of its own, so its career ladder
      // borrowed "Offensive Security / Pentesting" and told students the job needs
      // red teaming and Metasploit. It is a defensive, operational discipline:
      // find, rate, prioritise, get it patched, prove it is gone.
      category: 'Vulnerability Management',
      skills: [
        { key: 'vulnerability management', label: 'Vulnerability management', aliases: ['schwachstellenmanagement', 'vulnerability mgmt'] },
        { key: 'vulnerability scanning', label: 'Vulnerability scanning', aliases: ['schwachstellenscan', 'vulnerability scan'] },
        { key: 'nessus', label: 'Nessus' },
        { key: 'qualys', label: 'Qualys' },
        { key: 'openvas', label: 'OpenVAS / Greenbone', aliases: ['greenbone'] },
        { key: 'cvss', label: 'CVSS scoring', aliases: ['cvss score'] },
        { key: 'cve', label: 'CVE / NVD research', aliases: ['nvd', 'cve analysis'] },
        { key: 'patch management', label: 'Patch management', aliases: ['patchmanagement', 'patch-management', 'sicherheits-patches', 'sicherheitspatches'] },
        { key: 'remediation tracking', label: 'Remediation tracking', aliases: ['nachbesserungen'] },
        { key: 'asset inventory', label: 'Asset inventory', aliases: ['asset management', 'cmdb', 'bestandsaufnahme', 'inventarisierung'] },
        { key: 'risk prioritisation', label: 'Risk-based prioritisation', aliases: ['risk prioritization'] },
        { key: 'attack surface management', label: 'Attack surface management', aliases: ['asm', 'angriffsflächenmanagement'] },
        { key: 'security baselines', label: 'Security baselines / hardening', aliases: ['cis benchmarks', 'bsi grundschutz', 'sicherheitsstandards', 'sicherheitsvorgaben'] },
        { key: 'vulnerability reporting', label: 'Vulnerability reporting' },
      ],
    },
    {
      category: 'Malware Analysis & Reverse Engineering',
      skills: [
        { key: 'malware analysis', label: 'Malware analysis', aliases: ['schadsoftware-analyse', 'malware-analyse'] },
        { key: 'reverse engineering', label: 'Reverse engineering', aliases: ['reverse engineerieng', 'rückwärtsanalyse'] },
        { key: 'static analysis', label: 'Static malware analysis', aliases: ['statische analyse'] },
        { key: 'dynamic analysis', label: 'Dynamic malware analysis', aliases: ['dynamische analyse'] },
        { key: 'ida pro', label: 'IDA Pro' },
        { key: 'ghidra', label: 'Ghidra' },
        { key: 'x64dbg', label: 'x64dbg / OllyDbg' },
        { key: 'sandboxing', label: 'Sandboxing (Cuckoo)', aliases: ['sandbox'] },
        { key: 'assembly', label: 'Assembly language' },
        { key: 'obfuscation', label: 'Code obfuscation / unpacking', aliases: ['verschleierung'] },
        { key: 'ransomware analysis', label: 'Ransomware analysis' },
        { key: 'shellcode', label: 'Shellcode analysis' },
      ],
    },
    {
      category: 'Operating Systems & Infrastructure',
      skills: [
        { key: 'linux', label: 'Linux administration' },
        { key: 'linux hardening', label: 'Linux hardening', aliases: ['linux-härtung'] },
        { key: 'windows hardening', label: 'Windows hardening', aliases: ['windows-härtung'] },
        { key: 'windows server', label: 'Windows Server' },
        { key: 'bash', label: 'Bash scripting' },
        { key: 'powershell', label: 'PowerShell' },
        { key: 'python', label: 'Python' },
        { key: 'system administration', label: 'System administration', aliases: ['systemadministration', 'systemadministrator', 'systembetreuung'] },
        { key: 'patch management', label: 'Patch management' },
        { key: 'vulnerability management', label: 'Vulnerability management' },
        { key: 'configuration management', label: 'Secure configuration management', aliases: ['konfigurationsmanagement'] },
        { key: 'group policy', label: 'Group Policy (GPO)', aliases: ['gruppenrichtlinien'] },
        { key: 'endpoint security', label: 'Endpoint security', aliases: ['endpunktsicherheit'] },
        { key: 'antivirus', label: 'Antivirus / EPP' },
        { key: 'backup', label: 'Backup & recovery', aliases: ['datensicherung', 'sicherung'] },
      ],
    },
    {
      category: 'OT / IoT / Mobile Security',
      skills: [
        { key: 'ot security', label: 'OT / ICS security', aliases: ['ot-sicherheit', 'anlagensicherheit'] },
        { key: 'scada', label: 'SCADA security' },
        { key: 'iot security', label: 'IoT security', aliases: ['iot-sicherheit'] },
        { key: 'mobile security', label: 'Mobile security', aliases: ['mobile sicherheit'] },
        { key: 'android security', label: 'Android security', aliases: ['android-sicherheit', 'android reverse engineering', 'android reverse engineerieng'] },
        { key: 'ios security', label: 'iOS security' },
        { key: 'embedded security', label: 'Embedded security', aliases: ['embedded-sicherheit', 'eingebettete sicherheit'] },
        { key: 'firmware analysis', label: 'Firmware analysis', aliases: ['firmware-analyse'] },
        { key: 'automotive security', label: 'Automotive security', aliases: ['fahrzeugsicherheit'] },
        { key: 'modbus', label: 'Modbus / industrial protocols' },
      ],
    },
    {
      category: 'Certifications',
      skills: [
        { key: 'comptia security+', label: 'CompTIA Security+' },
        { key: 'comptia cysa+', label: 'CompTIA CySA+' },
        { key: 'comptia pentest+', label: 'CompTIA PenTest+' },
        { key: 'cissp', label: 'CISSP' },
        { key: 'ccsp', label: 'CCSP' },
        { key: 'cism', label: 'CISM' },
        { key: 'cisa', label: 'CISA' },
        { key: 'ceh', label: 'CEH (Certified Ethical Hacker)' },
        { key: 'oscp', label: 'OSCP' },
        { key: 'oswe', label: 'OSWE' },
        { key: 'gcih', label: 'GIAC GCIH' },
        { key: 'gpen', label: 'GIAC GPEN' },
        { key: 'gsec', label: 'GIAC GSEC' },
        { key: 'crisc', label: 'CRISC' },
        { key: 'security+ ce', label: 'Security+ CE' },
        { key: 'aws certified security', label: 'AWS Certified Security' },
        { key: 'azure security engineer', label: 'Azure Security Engineer (AZ-500)' },
        { key: 'iso 27001 lead auditor', label: 'ISO 27001 Lead Auditor' },
        { key: 'bsi grundschutz praktiker', label: 'BSI Grundschutz-Praktiker' },
      ],
    },
    {
      category: 'Professional & Soft Skills',
      skills: [
        { key: 'communication', label: 'Communication', aliases: ['kommunikationsfähigkeit', 'kommunikationsfreude'] },
        { key: 'teamwork', label: 'Teamwork', aliases: ['teamfähigkeit', 'teamfähig', 'teamarbeit', 'im team'] },
        { key: 'documentation', label: 'Technical documentation', aliases: ['dokumentation'] },
        { key: 'problem solving', label: 'Problem solving', aliases: ['problemlösung', 'problemlösungskompetenz'] },
        { key: 'analytical thinking', label: 'Analytical thinking', aliases: ['analytisches denken', 'analytisches verständnis'] },
        { key: 'project management', label: 'Project management', aliases: ['projektmanagement', 'projektmanagementmethode'] },
        { key: 'stakeholder management', label: 'Stakeholder management', aliases: ['stakeholder-management'] },
        { key: 'report writing', label: 'Security report writing', aliases: ['berichtserstellung', 'berichte'] },
        { key: 'presentation', label: 'Presentation skills', aliases: ['präsentation'] },
        { key: 'continuous learning', label: 'Continuous learning', aliases: ['weiterbildung', 'weiterbildungsmotivation', 'lernbereitschaft', 'schulungen', 'schulung'] },
      ],
    },
  ];

  // A few extended security roles for richer gap analysis.
  const SECURITY_ROLES = [
    { name: 'SOC Analyst (Tier 1)', required: ['siem', 'log analysis', 'incident response', 'security monitoring', 'communication'] },
    { name: 'Penetration Tester', required: ['penetration testing', 'metasploit', 'nmap', 'burp suite', 'privilege escalation'] },
    { name: 'Cloud Security Engineer', required: ['cloud security', 'aws security', 'kubernetes security', 'iam policies', 'terraform'] },
    { name: 'Incident Responder (DFIR)', required: ['incident response', 'digital forensics', 'memory forensics', 'threat intelligence', 'log analysis'] },
    { name: 'GRC / Security Consultant', required: ['risk assessment', 'iso 27001', 'gdpr', 'audit', 'security policies'] },
    { name: 'Application Security Engineer', required: ['owasp', 'sast', 'secure coding', 'threat modeling', 'api security'] },
    { name: 'Malware Analyst', required: ['malware analysis', 'reverse engineering', 'ghidra', 'static analysis', 'assembly'] },
  ];

  return { SECURITY_GROUPS, SECURITY_ROLES };
});
